image: markussh/bsv_riscv-gcc:latest

variables:
  XILINX_VIVADO: "/opt/cad/xilinx/vitis/Vivado/2020.2"
  XILINX_LICENSE_FILE: "/opt/cad/keys/xilinx"

stages:
  - deps
  - test

before_script:
  # Vivado
  - export PATH="${XILINX_VIVADO}/bin:${PATH}:/opt/bsc/bin"
  - export LC_ALL=C
  - export PATH="/opt/cad/mentor/questa/latest/questasim/bin/:${PATH}"
  - export MGLS_LICENSE_FILE=/opt/cad/keys/mentor
  - yum -y install git make wget bzip2 redhat-lsb-core gcc libX11 libXext libXft python3


deps:
  stage: deps
  script:

  # BSV tools
  - pushd tests/project
  - /opt/bsvtools/bsvAdd.py
  - mkdir -p libraries/
  - pushd libraries
  - git clone https://github.com/esa-tu-darmstadt/BlueLib.git
  - popd
  - popd
  
  artifacts:
    paths:
      - tests/project/.bsv_tools
      - tests/project/libraries/BlueLib

test_sram22:
  stage: test
  script:

  - pushd tests/project
  - mkdir -p libraries/bluesram/
  - cp ../../* libraries/bluesram/ -r || true
  - pushd libraries/bluesram
  - python3 create_wrappers_sky130.py --sram22 ../../../sram22/test_instances
  - popd
  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=6 DW=32 P_R=0 P_W=0 P_RW=1 STRB=8
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=6 DW=32 P_R=0 P_W=0 P_RW=1 STRB=8

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=6 DW=64 P_R=0 P_W=0 P_RW=1 STRB=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=6 DW=64 P_R=0 P_W=0 P_RW=1 STRB=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=9 DW=32 P_R=0 P_W=0 P_RW=1 STRB=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=9 DW=32 P_R=0 P_W=0 P_RW=1 STRB=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=6 DW=32 P_R=0 P_W=0 P_RW=1 STRB=32
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=6 DW=32 P_R=0 P_W=0 P_RW=1 STRB=32

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=9 DW=8 P_R=0 P_W=0 P_RW=1 STRB=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=9 DW=8 P_R=0 P_W=0 P_RW=1 STRB=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=6 DW=32 P_R=0 P_W=0 P_RW=1 STRB=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=6 DW=32 P_R=0 P_W=0 P_RW=1 STRB=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=9 DW=32 P_R=0 P_W=0 P_RW=1 STRB=2
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=9 DW=32 P_R=0 P_W=0 P_RW=1 STRB=2

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=7 DW=32 P_R=0 P_W=0 P_RW=1 STRB=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=7 DW=32 P_R=0 P_W=0 P_RW=1 STRB=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=9 DW=32 P_R=0 P_W=0 P_RW=1 STRB=8
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=9 DW=32 P_R=0 P_W=0 P_RW=1 STRB=8

  - make SIM_TYPE=VERILOG GUARD=0 RAM=SRAM22 AW=9 DW=32 P_R=0 P_W=0 P_RW=1 STRB=4
  - make SIM_TYPE=VERILOG GUARD=1 RAM=SRAM22 AW=9 DW=32 P_R=0 P_W=0 P_RW=1 STRB=4
  - popd

test_openram:
  stage: test
  script:

  - pushd tests/project
  - mkdir -p libraries/bluesram/
  - cp ../../* libraries/bluesram/ -r || true
  - pushd libraries/bluesram
  - python3 create_wrappers_sky130.py ../../../openram/test_instances
  - popd
  - make SIM_TYPE=VERILOG GUARD=0 RAM=OPENRAM AW=10 DW=8 P_R=1 P_W=1 P_RW=0 STRB=0 TEST_W=1 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=OPENRAM AW=10 DW=8 P_R=1 P_W=1 P_RW=0 STRB=0 TEST_W=1 TEST_R=1
  
  - make SIM_TYPE=VERILOG GUARD=0 RAM=OPENRAM AW=5 DW=9 P_R=0 P_W=0 P_RW=1 STRB=4
  - make SIM_TYPE=VERILOG GUARD=1 RAM=OPENRAM AW=5 DW=9 P_R=0 P_W=0 P_RW=1 STRB=4

  - make SIM_TYPE=VERILOG GUARD=0 RAM=OPENRAM AW=10 DW=8 P_R=1 P_W=0 P_RW=1 STRB=0 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=OPENRAM AW=10 DW=8 P_R=1 P_W=0 P_RW=1 STRB=0 TEST_R=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=OPENRAM AW=4 DW=8 P_R=1 P_W=0 P_RW=1 STRB=0 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=OPENRAM AW=4 DW=8 P_R=1 P_W=0 P_RW=1 STRB=0 TEST_R=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=OPENRAM AW=9 DW=32 P_R=1 P_W=0 P_RW=1 STRB=4 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=OPENRAM AW=9 DW=32 P_R=1 P_W=0 P_RW=1 STRB=4 TEST_R=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=OPENRAM AW=8 DW=32 P_R=1 P_W=0 P_RW=1 STRB=4 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=OPENRAM AW=8 DW=32 P_R=1 P_W=0 P_RW=1 STRB=4 TEST_R=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=OPENRAM AW=7 DW=32 P_R=1 P_W=0 P_RW=1 STRB=0 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=OPENRAM AW=7 DW=32 P_R=1 P_W=0 P_RW=1 STRB=0 TEST_R=1

  - make SIM_TYPE=VERILOG GUARD=0 RAM=OPENRAM AW=4 DW=8 P_R=1 P_W=0 P_RW=1 STRB=4 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=OPENRAM AW=4 DW=8 P_R=1 P_W=0 P_RW=1 STRB=4 TEST_R=1
  - popd

test_BRAMDP:
  stage: test
  script:

  - pushd tests/project
  - mkdir -p libraries/bluesram/
  - cp ../../* libraries/bluesram/ -r || true
  - pushd libraries/bluesram
  - python3 create_wrappers_sky130.py ../../../openram/test_instances
  - popd
  - make SIM_TYPE=VERILOG GUARD=0 RAM=BRAMDP AW=10 DW=8 P_R=1 P_W=1 P_RW=0 STRB=0 TEST_W=1 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=BRAMDP AW=10 DW=8 P_R=1 P_W=1 P_RW=0 STRB=0 TEST_W=1 TEST_R=1
  
  - make SIM_TYPE=VERILOG GUARD=0 RAM=BRAMDP AW=5 DW=9 P_R=0 P_W=0 P_RW=1 STRB=0
  - make SIM_TYPE=VERILOG GUARD=1 RAM=BRAMDP AW=5 DW=9 P_R=0 P_W=0 P_RW=1 STRB=0

  - popd

test_BRAMSP:
  stage: test
  script:

  - pushd tests/project
  - mkdir -p libraries/bluesram/
  - cp ../../* libraries/bluesram/ -r || true
  - pushd libraries/bluesram
  - python3 create_wrappers_sky130.py ../../../openram/test_instances
  - popd
  
  - make SIM_TYPE=VERILOG GUARD=0 RAM=BRAMSP AW=5 DW=9 P_R=0 P_W=0 P_RW=1 STRB=0
  - make SIM_TYPE=VERILOG GUARD=1 RAM=BRAMSP AW=5 DW=9 P_R=0 P_W=0 P_RW=1 STRB=0

  - popd

test_BRAMDPBE:
  stage: test
  script:

  - pushd tests/project
  - mkdir -p libraries/bluesram/
  - cp ../../* libraries/bluesram/ -r || true
  - pushd libraries/bluesram
  - python3 create_wrappers_sky130.py ../../../openram/test_instances
  - popd
  - make SIM_TYPE=VERILOG GUARD=0 RAM=BRAMDPBE AW=10 DW=32 P_R=1 P_W=1 P_RW=0 STRB=4 TEST_W=1 TEST_R=1
  - make SIM_TYPE=VERILOG GUARD=1 RAM=BRAMDPBE AW=10 DW=32 P_R=1 P_W=1 P_RW=0 STRB=4 TEST_W=1 TEST_R=1
  
  - make SIM_TYPE=VERILOG GUARD=0 RAM=BRAMDPBE AW=5 DW=32 P_R=0 P_W=0 P_RW=1 STRB=4
  - make SIM_TYPE=VERILOG GUARD=1 RAM=BRAMDPBE AW=5 DW=32 P_R=0 P_W=0 P_RW=1 STRB=4

  - popd

test_BRAMSPBE:
  stage: test
  script:

  - pushd tests/project
  - mkdir -p libraries/bluesram/
  - cp ../../* libraries/bluesram/ -r || true
  - pushd libraries/bluesram
  - python3 create_wrappers_sky130.py ../../../openram/test_instances
  - popd
  
  - make SIM_TYPE=VERILOG GUARD=0 RAM=BRAMSPBE AW=5 DW=32 P_R=0 P_W=0 P_RW=1 STRB=4
  - make SIM_TYPE=VERILOG GUARD=1 RAM=BRAMSPBE AW=5 DW=32 P_R=0 P_W=0 P_RW=1 STRB=4

  - popd
